[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://gmvqcycnppuzixugzxvy.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtdnFjeWNucHB1eml4dWd6eHZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMTU0NzYsImV4cCI6MjA2Nzg5MTQ3Nn0.5NodA2qksds_fUdlzgx7OZnN8OvzHitzdSvTdBWqoo8"
  NEXT_PUBLIC_APP_URL = "https://생각습관.com"
  NEXT_PUBLIC_APP_NAME = "생각습관"
  NEXT_PUBLIC_DOMAIN = "생각습관.com"
  NEXT_PUBLIC_DOMAIN_KOREAN = "생각습관.com"
  NEXT_PUBLIC_DOMAIN_ENGLISH = "thinking-habits.com"
  NEXT_PUBLIC_TRADEMARK = "생각습관™"
  NEXT_PUBLIC_COPYRIGHT = "© 2025 생각습관"
  NEXT_PUBLIC_GOOGLE_CLIENT_ID = "561674856347-1h8o27r9lp59dm80ieumm8q70pgud4qe.apps.googleusercontent.com"
  NEXTAUTH_URL = "https://생각습관.com"
  NEXT_PUBLIC_UPLOAD_MAX_SIZE = "5242880"
  NEXT_PUBLIC_ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/gif,application/pdf"
  NEXT_PUBLIC_ENABLE_COMMUNITY = "true"
  NEXT_PUBLIC_ENABLE_NOTIFICATIONS = "true"
  NEXT_PUBLIC_ENABLE_FILE_UPLOAD = "true"

[[redirects]]
  from = "/download"
  to = "/downloads"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"