import { DiagnosticQuestion } from '@/types/diagnosis';

export const mockQuestions: DiagnosticQuestion[] =
  [
    {
      id: 'perfectionism_1',
      text: '일을 할 때 완벽하지 않으면 의미가 없다고 생각한다',
      category: 'perfectionism',
      type: 'two_stage_rating',
      required: true,
      two_stage_config: {
        stage1_labels: ['상', '중', '하'],
        stage2_labels: ['상', '중', '하'],
        final_scale: 9,
        stage1_instruction: '먼저 전반적인 수준을 선택해주세요',
        stage2_instruction: '선택한 범위 내에서 더 구체적으로 평가해주세요',
      },
      section_title: '완벽주의 성향',
      help_text: '완벽하지 않으면 의미가 없다고 느끼는 정도를 평가해주세요.',
    },
    {
      id: 'perfectionism_2',
      text: '실수를 하면 자신을 심하게 비난한다',
      category: 'perfectionism',
      type: 'two_stage_rating',
      required: true,
      two_stage_config: {
        stage1_labels: ['상', '중', '하'],
        stage2_labels: ['상', '중', '하'],
        final_scale: 9,
        stage1_instruction: '먼저 전반적인 수준을 선택해주세요',
        stage2_instruction: '선택한 범위 내에서 더 구체적으로 평가해주세요',
      },
      section_title: '완벽주의 성향',
      help_text: '실수에 대한 자기 비난의 정도를 평가해주세요.',
    },
    {
      id: 'blackwhite_1',
      text: '사람이나 상황을 좋거나 나쁘게만 판단한다',
      category: 'blackwhite',
      type: 'two_stage_rating',
      required: true,
      two_stage_config: {
        stage1_labels: ['상', '중', '하'],
        stage2_labels: ['상', '중', '하'],
        final_scale: 9,
        stage1_instruction: '먼저 전반적인 수준을 선택해주세요',
        stage2_instruction: '선택한 범위 내에서 더 구체적으로 평가해주세요',
      },
      section_title: '흑백논리 성향',
      help_text: '극단적으로 판단하는 경향의 정도를 평가해주세요.',
    },
    {
      id: 'catastrophic_1',
      text: '작은 문제가 생기면 최악의 상황을 먼저 생각한다',
      category: 'catastrophic',
      type: 'two_stage_rating',
      required: true,
      two_stage_config: {
        stage1_labels: ['상', '중', '하'],
        stage2_labels: ['상', '중', '하'],
        final_scale: 9,
        stage1_instruction: '먼저 전반적인 수준을 선택해주세요',
        stage2_instruction: '선택한 범위 내에서 더 구체적으로 평가해주세요',
      },
      section_title: '파국적 사고 성향',
      help_text: '최악의 상황을 먼저 떠올리는 정도를 평가해주세요.',
    },
    {
      id: 'personalization_1',
      text: '나쁜 일이 생기면 내 탓이라고 생각한다',
      category: 'personalization',
      type: 'two_stage_rating',
      required: true,
      two_stage_config: {
        stage1_labels: ['상', '중', '하'],
        stage2_labels: ['상', '중', '하'],
        final_scale: 9,
        stage1_instruction: '먼저 전반적인 수준을 선택해주세요',
        stage2_instruction: '선택한 범위 내에서 더 구체적으로 평가해주세요',
      },
      section_title: '개인화 사고 성향',
      help_text: '모든 것을 자신의 탓으로 돌리는 정도를 평가해주세요.',
    },
    {
      id: 'emotional_1',
      text: '기분이 나쁘면 실제로 나쁜 일이 일어날 것이라고 생각한다',
      category: 'emotional',
      type: 'two_stage_rating',
      required: true,
      two_stage_config: {
        stage1_labels: ['상', '중', '하'],
        stage2_labels: ['상', '중', '하'],
        final_scale: 9,
        stage1_instruction: '먼저 전반적인 수준을 선택해주세요',
        stage2_instruction: '선택한 범위 내에서 더 구체적으로 평가해주세요',
      },
      section_title: '감정적 추론 성향',
      help_text: '감정을 근거로 판단하는 정도를 평가해주세요.',
    },
    {
      id: 'perfectionism_3',
      text: '완벽하게 할 수 없다면 아예 시작하지 않는다',
      category: 'perfectionism',
      type: 'two_stage_rating',
      required: true,
      two_stage_config: {
        stage1_labels: ['상', '중', '하'],
        stage2_labels: ['상', '중', '하'],
        final_scale: 9,
        stage1_instruction: '먼저 전반적인 수준을 선택해주세요',
        stage2_instruction: '선택한 범위 내에서 더 구체적으로 평가해주세요',
      },
      section_title: '완벽주의 성향',
      help_text: '완벽하지 않으면 시작하지 않는 정도를 평가해주세요.',
    },
    {
      id: 'blackwhite_2',
      text: '중간 지점이나 회색 영역을 인정하기 어렵다',
      category: 'blackwhite',
      type: 'two_stage_rating',
      required: true,
      two_stage_config: {
        stage1_labels: ['상', '중', '하'],
        stage2_labels: ['상', '중', '하'],
        final_scale: 9,
        stage1_instruction: '먼저 전반적인 수준을 선택해주세요',
        stage2_instruction: '선택한 범위 내에서 더 구체적으로 평가해주세요',
      },
      section_title: '흑백논리 성향',
      help_text: '중간 지점을 인정하기 어려운 정도를 평가해주세요.',
    },
  ];
